config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }

   root to: "static_pages#index"

   get "crypto", to: "static_pages#crypto"

   get :day_game, to: "static_pages#day_game"
   get :messages, to: "static_pages#messages"
   get :play_game, to: "games#show"
   get :win_game, to: "games#win"
   get :game_over, to: "games#game_over"

   resources :games, only: [ :show, :update ]
   resources :guest_users, only: [ :show, :update ]

   resources :top_players, only: :index

   resources :boards, only: [ :index ] do
     resources :top_players, only: :index
   end

   resources :users, only: [:update, :show]

   # Cryto
   resources :notifications
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  #skip_before_action :authenticate_user!

  def index
    if current_user
      redirect_to user_path(current_user)
    end
  end

  def coming_soon
  end

  def crypto
    @crypto_service = CryptoService.new
    @notifications = Notification.order(:created_at)
    CryptoJob.perform_later
  end

  def day_game
    render :coming_soon
  end

  def messages
    render :coming_soon
  end
end

app/views/static_pages/coming_soon.html.haml
= content_for :header do
  Coming Soon!

app/views/static_pages/crypto.html.haml
= content_for :header do
  Exchange Rates

%table.table-fixed
  %tr
    %th Actions
    %th Currency
    %th ($) Price
  - @crypto_service.tradable_currencies.each do |currency|
    %tr.my-8
      %td
        = link_to "Notify",
          new_notification_path(code: currency[2]),
          class: "button green sm m-2"
      %td.text-xl
        = currency[0]
      %td.text-green-400.text-lg{style:"text-align:right"}
        = currency[1]

= render "shared/header", title: "Notifications"

%ul
  - @notifications.each do |notification|
    %li
      = link_to "Edit", edit_notification_path(notification)
      Notify when
      = Currency::TRADABLE[notification.code.to_sym]
      is
      = notification.comparison
      = number_to_currency notification.price
      = button_to "Destroy",
        notification_path(notification),
        class: 'button red',
        method: :delete,
          data: { confirm: "Are you sure?" }

app/views/static_pages/index.html.haml
= content_for :header do
  Welcome to Mine Swept

= render "shared/play_game"

.block
  = render "shared/sign_up_blurb"