config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }

   root to: "static_pages#index"

   get "crypto", to: "static_pages#crypto"

   get :day_game, to: "static_pages#day_game"
   get :messages, to: "static_pages#messages"
   get :play_game, to: "games#show"
   get :win_game, to: "games#win"
   get :game_over, to: "games#game_over"

   resources :games, only: [ :show, :update ]
   resources :guest_users, only: [ :show, :update ]

   resources :top_players, only: :index

   resources :boards, only: [ :index ] do
     resources :top_players, only: :index
   end

   resources :users, only: [:update, :show]

   # Cryto
   resources :notifications
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :player_boards, inverse_of: :board, dependent: :restrict_with_error
  has_many :games, dependent: :restrict_with_error

  def self.where_difficulty(difficulty)
    obj = BoardGenerator.new(difficulty: difficulty)
    size = obj.size

    where(
      width: size,
      width: size,
      bomb_count: obj.get_bomb_count,
    )
  end

  def won?(state)
    playable_spots_count == state.sum do |_row_index, row|
      row.count
    end
  end

  def playable_spots_count
    spot_count - bomb_count
  end

  def spot_count
    width * height
  end

  def game_over?(state)
    bomb_coords.each do |coord|
      y = coord[0]
      x = coord[1]

      return true if state[y] && state[y][x].present?
    end

    false
  end

  def bomb_value
    @bomb_value ||= BoardGenerator.new.bomb
  end

  def bomb_coords
    rows.map do |row_index, row|
      bombs = []
      row.each do |spot_index, spot|
        bombs << [row_index, spot_index] if spot.to_sym == bomb_value.to_sym
      end

      bombs
    end.flatten(1)
  end
end

app/helpers/board_helper.rb
module BoardHelper
  def spot_revealed?(game, y, x)
    return false unless row = game.board_state[y]

    row[x].present?
  end

  def input_name(y, x)
    "board_state[#{y}][#{x}]"
  end

  def default_data_options(is_spot_revealed, value)
    { revealed: is_spot_revealed.to_s,
      value: value,
      target: "board.spot" }
  end

  def form_btn_type(btn_is_bomb)
    btn_is_bomb ? :button : :submit
  end

  def spot_text(board_revealed, spot_revealed, value)
    blank = "&nbsp;"

    return blank unless board_revealed || spot_revealed

    value || blank
  end
end

app/views/boards/_board.html.haml
- helper = BoardGenerator.new(difficulty: game.difficulty)
- revealed ||= false
- won  ||= false
- form_url = game_over_path
- width = game.board.width
- height = game.board.height
- board_options  = { id: game.board.id,
                     flag: "🏁",
                     seconds: seconds,
                     coords: helper.touching_coords.to_json }

%div{ data: { revealed: revealed.to_s,
              won: local_assigns[:won].to_s,
              controller: :board,
              board:  board_options } }

  %div.timer
    Seconds:
    %span{ data: { target: "board.timer" } }
      = seconds
    - if revealed
      %span
        Your Time:
        = time

  = form_with(class: "flex flex-col space-y-1", model: game, disabled: revealed) do |f|
    - game.board.rows.each do |row_index, row|
      %div{class: "flex flex-row flex-nowrap items-center justify-center space-x-1", data: {target: "board.row"}}
        = render partial: "boards/spot",
          collection: (0...width).to_a,
          locals: { f: f,
                    row: row,
                    game: game,
                    row_index: row_index,
                    helper: helper,
                    revealed: revealed }

app/views/boards/_spot.html.haml
- index = spot_counter
- is_bomb = (row[index.to_s].to_s == helper.bomb.to_s)
- spot_is_revealed = spot_revealed?(game, row_index.to_s, index.to_s)
- value = is_bomb ? "💣" : row[index.to_s]

- spot_is_disabled = revealed || spot_is_revealed
- data = default_data_options(spot_is_revealed, value)
- data[:target] << " board.bomb" if is_bomb
- data[:action] = "click->board#reveal contextmenu->board#flag"

%div{class: "flex-shrink h-10 w-10 shadow-lg", data: data}
  = f.hidden_field input_name(row_index, index),
    value: true, disabled: revealed || !spot_is_revealed

  %button{class: "w-full h-full", type: :submit, disabled: spot_is_disabled}
    = spot_text(revealed, spot_is_revealed, value).html_safe