config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }

   root to: "static_pages#index"

   get "crypto", to: "static_pages#crypto"

   get :day_game, to: "static_pages#day_game"
   get :messages, to: "static_pages#messages"
   get :play_game, to: "games#show"
   get :win_game, to: "games#win"
   get :game_over, to: "games#game_over"

   resources :games, only: [ :show, :update ]
   resources :guest_users, only: [ :show, :update ]

   resources :top_players, only: :index

   resources :boards, only: [ :index ] do
     resources :top_players, only: :index
   end

   resources :users, only: [:update, :show]

   # Cryto
   resources :notifications
end

app/views/layouts/_footer.html.haml
%footer.border-t.border-gray-400
  .container.max-w-md.mx-auto.flex.py-8
    .w-full.mx-auto.flex.flex-wrap
      .flex.w-full{:class => "md:w-1/2"}
        .px-8
          %h3.font-bold.font-bold.text-gray-100
            = ENV["APP_NAME"]
          %p.py-4.text-gray-600.text-sm
            = t(:footer_blurb)

      .flex.w-full{:class => "md:w-1/2"}
        .px-8
          %h3.font-bold.font-bold.text-gray-100 Links
          %ul.list-reset.items-center.text-sm.pt-3
            %li.flex.items-center.group.border-indigo-500.hover:shadow-lg.hover:border-transparent{:class => "..."}
              %i.fa.fa-envelope.fa-fw.mr-3{ class: "group-hover:text-green-400" }
              %a.text-gray-600.group-hover:text-underline{:class => "...",
                href: "mailto:#{ENV["EMAIL"]}"}
                admin@mineswept.io

app/views/layouts/_navigation.html.haml
%nav#header.dark:bg-gray-800.fixed.w-full.z-10.top-0
  .w-full.container.mx-auto.flex.flex-wrap.items-center.mt-0.pt-3.pb-3.lg:pb-0
    .pl-2.md:pl-0{:class => "w-1/2"}
      %a.text-gray-100.text-base.xl:text-xl.no-underline.hover:no-underline.font-bold{:href => "/"}
        %i.fas.fa-broom.text-blue-400.pr-3{style: "font-size: 20px !important;"}
        = ENV["APP_NAME"]
    .pr-0{:class => "w-1/2"}
      .flex.relative.inline-block.float-right
        .relative.text-sm.text-gray-100
          %button#userButton.flex.items-center.focus:outline-none.mr-3
            %img.w-8.h-8.rounded-full.mr-4{:alt => "Avatar of User", :src => "/avatar.jpeg"}/
            %span.hidden.md:inline-block.text-gray-100
              = "#{t(:hello)}, #{user_display_name}"
            - if current_user
              %svg.pl-2.h-2.fill-current.text-gray-100{"enable-background" => "new 0 0 129 129", :version => "1.1", :viewbox => "0 0 129 129", :xmlns => "http://www.w3.org/2000/svg", "xmlns:xlink" => "http://www.w3.org/1999/xlink"}
                %g
                  %path{:d => "m121.3,34.6c-1.6-1.6-4.2-1.6-5.8,0l-51,51.1-51.1-51.1c-1.6-1.6-4.2-1.6-5.8,0-1.6,1.6-1.6,4.2 0,5.8l53.9,53.9c0.8,0.8 1.8,1.2 2.9,1.2 1,0 2.1-0.4 2.9-1.2l53.9-53.9c1.7-1.6 1.7-4.2 0.1-5.8z"}
          #userMenu.bg-gray-800.rounded.shadow-md.mt-2.absolute.mt-12.top-0.right-0.min-w-full.overflow-auto.z-30.invisible
            %ul.list-reset.w-52
              - if user = current_user
                - if user.play_count.positive?
                  .px-10.whitespace-nowrap
                    = render "users/stats", model: user
                - if user.playing_game?
                  %li
                    = link_to("Current Game", play_game_path, class: "px-4 py-2 block text-gray-100 hover:bg-gray-700 no-underline hover:no-underline")
                    .px-6.pb-2
                      \%
                      = user.game.percent_complete
                      complete
                  %li
                    %hr.border-t.mx-2.border-gray-400/

                %li
                  = link_to("Home", user_path(current_or_guest_user), class: "px-4 py-2 block text-gray-100 hover:bg-gray-700 no-underline hover:no-underline")
                %li
                  = link_to("Account", edit_user_registration_path, class: "px-4 py-2 block text-gray-100 hover:bg-gray-700 no-underline hover:no-underline")
                %li
                  = link_to("Sign Out", destroy_user_session_path, class: "px-4 py-2 block text-gray-100 hover:bg-gray-700 no-underline hover:no-underline",method: :delete)
        .block.lg:hidden.pr-4
          %button#nav-toggle.flex.items-center.px-3.py-2.border.rounded.text-gray-500.border-gray-600.hover:text-gray-100.hover:border-teal-500.appearance-none.focus:outline-none
            %svg.fill-current.h-3.w-3{:viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
              %title Menu
              %path{:d => "M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"}
    #nav-content.w-full.flex-grow.lg:flex.lg:items-center.lg:w-auto.hidden.lg:block.mt-2.lg:mt-0.z-20
      %ul.list-reset.lg:flex.flex-1.items-center.px-4.md:px-0
        %li.mr-6.my-2.md:my-0
          %a.block.py-1.md:py-3.pl-1.align-middle.no-underline.hover:text-gray-100.border-b-2.border-gray-800.hover:border-green-400{:href => play_game_path,
            class: active_nav_class(play_game_path, "border-green-400")}
            %i{ class:"fas fa-caret-square-right mr-3 text-green-400"}
            %span.pb-1.md:pb-0.text-sm Play Game
        %li.mr-6.my-2.md:my-0
          %a.block.py-1.md:py-3.pl-1.align-middle.no-underline.hover:text-gray-100.border-b-2.border-gray-800.hover:border-blue-400{:href => "/",
            class: active_nav_class(home_path, "border-blue-400")}
            %i.fas.fa-home.fa-fw.mr-3.text-blue-400
            %span.pb-1.md:pb-0.text-sm Home
        %li.mr-6.my-2.md:my-0
          %a.block.py-1.md:py-3.pl-1.align-middle.text-gray-500.no-underline.hover:text-gray-100.border-b-2.border-gray-800.hover:border-pink-400{:href => top_players_path,
            class: active_nav_class(top_players_path, "border-pink-400")}
            %i.fas.fa-medal.fa-fw.mr-3.text-pink-400
            %span.pb-1.md:pb-0.text-sm Top Players
        %li.mr-6.my-2.md:my-0
          %a.block.py-1.md:py-3.pl-1.align-middle.text-gray-500.no-underline.hover:text-gray-100.border-b-2.border-gray-800.hover:border-red-400{:href => day_game_path,
            class: active_nav_class(day_game_path, "border-red-400")}
            %i{class: "fas fa-calendar-day mr-3 text-red-400"}
            %span.pb-1.md:pb-0.text-sm Game of the Day
        %li.mr-6.my-2.md:my-0
          %a.block.py-1.md:py-3.pl-1.align-middle.text-gray-500.no-underline.hover:text-gray-100.border-b-2.border-gray-800.hover:border-purple-400{:href => messages_path,
            class: active_nav_class(messages_path, "border-purple-400")}
            %i.fa.fa-envelope.fa-fw.mr-3.text-purple-400
            %span.pb-1.md:pb-0.text-sm Messages
      .relative.pull-right.pl-4.pr-4.pb-4.mt-4.md:pr-0
        - if current_user
          %div{data: {turbolinks: { permanent: true}}}
            = render "users/difficulty_form", model: current_user, size: :sm
        - else
          .flex.items-center
            = link_to("Sign In", new_user_session_path, class: "button sm mr-3")
            = link_to("Sign Up", new_user_registration_path, class: "button green sm")
      //  %input.w-full.bg-gray-900.text-sm.text-gray-400.transition.border.border-gray-800.focus:outline-none.focus:border-gray-600.rounded.py-1.px-2.pl-10.appearance-none.leading-normal{:placeholder => "Search", :type => "search"}/
      //  .absolute.search-icon{:style => "top: 0.375rem;left: 1.75rem;"}
      //    %svg.fill-current.pointer-events-none.text-gray-500.w-4.h-4{:viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
      //      %path{:d => "M12.9 14.32a8 8 0 1 1 1.41-1.41l5.35 5.33-1.42 1.42-5.33-5.34zM8 14A6 6 0 1 0 8 2a6 6 0 0 0 0 12z"}

app/views/layouts/application.html.haml
!!!
%html{class: "dark"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{name: "viewport", content:"width=device-width, initial-scale=1.0"}
    %meta{ "http-equiv" => "X-UA-Compatible", content: "ie=edge" }
    %title Mindswept
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    - if Rails.env.production?
      / Global site tag (gtag.js) - Google Analytics
      %script{:async => "", :src => "https://www.googletagmanager.com/gtag/js?id=G-WEHPKRKBF8"}
      :javascript
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-WEHPKRKBF8');

      - if ENV["TAG_MANAGER"] == "true"
        // Google Tag Manager
        :javascript
          (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
          new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
          j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
          'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
          })(window,document,'script','dataLayer','GTM-5QC4TBX');

    - if current_page?(play_game_path)
      %meta{ name:"turbolinks-visit-control", content:"reload" }

  %body{class: "dark:bg-gray-900 dark:text-gray-100", data: {controller: "nav"}}
    - if ENV["TAG_MANAGER"] == "true"
      / Google Tag Manager (noscript)
      %noscript
        %iframe{:height => "0", :src => "https://www.googletagmanager.com/ns.html?id=GTM-5QC4TBX", :style => "display:none;visibility:hidden", :width => "0"}

    = render "layouts/navigation"

    %div{class: "container w-full mx-auto my-20 lg:mt-40"}
      %div{ class: "w-full px-4 md:px-0 md:mt-8 mb-16" }
        = render "shared/header", title: (yield(:header))

        #toast_alerts.fixed.top-20.right-0.z-50{data: { target: "page-alerts.toasts"}}
          - flash.each do |notice, message|
            - unique_index = rand(1000)
            - context ||= :toast
            - notice = (notice.to_sym == :alert ? :warning : notice)
            - target ||= ("alert.#{context} alert.#{local_assigns[:permanent] ? :perm : :temp}")
            .alert-toast.m-4{data: { controller: :alert, target: target }}
              %input.hidden{id: "toast_alert#{unique_index}", :type => "checkbox"}/

              .alert-body{class: notice}
                %label{ class: "close",
                        for: "toast_alert#{unique_index}",
                        title: "close",
                        data: {action: "click->alert#remove"}}

                  %span.alert-message
                    = message

                  %span.close-toggle
                    %i{ class: "fas fa-times" }

        = yield

  = render "layouts/footer"